version: '3'
services:
  frontend:
    build: ./dockerfiles
    # Node.jsのグローバル変数です。開発用途なのでdevelopmentを指定します。
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    tty: true